spring:
  application:
    name: novel-api-gateway
  jackson:
    default-property-inclusion: non_null
  profiles:
    include: redis,dubbo

server:
  port: 8080

base:
  url: /api/app,/api/base

#address:
#  white:
#    list: 127.0.0.1,192.168.31.21
#  black:
#    list: 127.0.0.2,192.168.146.21
