spring:
  application:
    name: novel-service-book
  profiles:
    include: nsq,redis,mysql,dubbo

# 日志配置
logging:
  config: classpath:log4j2.xml
  level:
    root: info
    web: info

# 雪花算法配置
snowflake:
  machine-id: 1
  app-id: 1
