# NSQ
nsq:
  produce:
    host: 47.95.239.29
    port: 4150
  lookup:
    host: 47.95.239.29
    port: 4161

  topic: reptile_book_topic
  channel1: reptile_book_topic

spring:
  application:
    name: novel-service-reptile

# 日志配置
logging:
  config: classpath:log4j2.xml
  level:
    root: info
    web: info

# Dubbo、Nacos
nacos:
  service-address: 114.116.239.108
  port: 8848
dubbo:
  registry:
    address: nacos://${nacos.service-address}:${nacos.port}
  protocol:
    name: dubbo
    port: 20030
  scan:
    base-packages: com.novel.reptile.service.dubbo

# 雪花算法配置
snowflake:
  machine-id: 0
  app-id: 3
